name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tags
        id: meta
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          TIMESTAMP=$(date +%s)
          echo "commit_tag=mithleshdev/go-server:${COMMIT_SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "latest_tag=mithleshdev/go-server:latest" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub (or GHCR, AWS ECR, etc.)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.commit_tag }}
            ${{ steps.meta.outputs.latest_tag }}
